### ISSUE TITLE
Completion of TODO tasks

### ISSUE THREAD

**Issue by arnabghose997** [hypersign-protocol/hid-node#23]
Tasks:

- [x] Implement the logic for writing `[]*type.Signer` when the `VerificationMethod`(in old standard, 'PublicKey') of DIdDoc is `nil` (`x/ssi/keeper/verify.go`)
- [ ] Implement adding fee payer value without the usage of `msg.Creator` field in `func (msg *MsgCreateDID) GetSigners()` (`x/ssi/types/message_create_did.go`)
- [x] Once `controller` is used in the DIDdoc, implement the commented code which checks for `controller` length, and appends to `[]*Signers` list  in `func (msg *DidDocStruct) GetSigners()`  (`x/ssi/types/message_create_did.go`)
- [ ] Configure the Regex Pattern in `create-schema` to test for proper version number in Schema ID
- [ ] The type used for `property` field in the message `SchemaProperty` (file: `proto/ssi/v1/schema.proto`) needs to be of type that can handle dynamic objects
- [x] Current implementation requires all the DIDs present in the `controller` field to sign the `didDoc`. This needs to be changed into the case where either one of the DID Controllers are able to sign the DidDoc (Check  `VerifySignature()` and `VerifyIdentitySignature()` in `x/cheqd/keeper/verify.go`)

**Comment by arnabghose997** [comment]
All issues will tracked in seperated Issue cards
